### PR TITLE
Adding GTKHash and Htop

### PR DESCRIPTION
**Pull request by WRM-42**
I have done several tests on a virtual machine and both work as they should.

### CODE REVIEW

**Comment by Henryws** [comment]
You don't need to run `sudo mkdir /usr/src/pacstall/pkg`

**Comment by Henryws** [comment]
also it needs to run `make -j$(nproc)`

**Comment by Henryws** [comment]
Remove the sudo references, except for `sudo make install DESTDIR=...` and this is wrong: `sudo mv -BWT.png /usr/src/pacstall/gtkhash`. That would move the file `-BWT.png` to `/`

**Comment by Henryws** [comment]
Also make wget run with `-q` to make it quiet. Pacscripts should have no output

**Comment by Henryws** [comment]
Take a look at the checks. Disregard the ones about htop failing, look above that

**Comment by Henryws** [comment]
I looked at the `.desktop` file and it wants to use `/usr/src/pacstall/gtkhash/-BWT.png`. That symlinks to `/-BWT.png` in the root Linux directory. Put it somewhere else (hicolor perhaps) then I can merge it

**Comment by Henryws** [comment]
I mean like this: `mv -BWT.png /usr/src/pacstall/gtkhash/usr/share/icons/hicolor/128x128/apps`

**Comment by Henryws** [comment]
Question. Does installing it without the extra stuff (`.desktop`, `-BWT.png`) work and add a `.desktop` and an icon?

**Comment by WRM-42** [comment]
The GTKHash installation works without the extra stuff. By default, there is no icon and .desktop. I'm thinking of potentially removing them.

**Comment by WRM-42** [comment]
Well, I did it. You can merge the pull request now.

**Pull request merged**
