### PR TITLE
Add pyfetch

### PR DESCRIPTION
**Pull request by kreat0**
Hello, this adds pyfetch, a simple fetch tool.
Please mention any mistakes i made, since i am not running Ubuntu and i cant test the script.

### CODE REVIEW

**Comment by DanKGooGLy** [comment]
👎🏼

**Comment by Henryws** [comment]
Standard practice is to spin up an Ubuntu VM and test it. I won't merge unless you've done that first

**Review by wizard-28 — CHANGES_REQUESTED** [review]
Add an hash

**Comment by Henryws** [comment]
And it must install to `/usr/src/pacstall/pyfetch`

**Pull request closed without merging**
