### PR TITLE
Add emacs

### PR DESCRIPTION
**Pull request by wizard-28**
This adds GNU Emacs.
> An extensible, customizable, free/libre text editor — and more.

GitHub mirror repository: https://github.com/emacs-mirror/emacs

### CODE REVIEW

**Comment by wizard-28** [comment]
Oh wait

**Comment by Henryws** [comment]
What

**Comment by wizard-28** [comment]
Ok, just added the `name` field

**Comment by wizard-28** [comment]
Can merge now.

**Pull request merged**
