### PR TITLE
Add uwufetch

### PR DESCRIPTION
**Pull request by wizard-28**
Hi, this adds uwufetch (release version)
Github repo: https://github.com/TheDarkBug/uwufetch

### CODE REVIEW

**Comment by wizard-28** [comment]
I've tested it, it works already!

**Comment by wizard-28** [comment]
By the way, is there a way to add **optional dependencies** in this case such as:
1. [ishw](https://github.com/lyonel/lshw) -> Better GPU detection.
2. [viu](https://github.com/atanunq/viu) -> Display distro logos as images

These are not hard dependencies but are needed for the aforementioned features, any way to add them?

**Comment by Henryws** [comment]
I can work on opt dependencies but for know you should just add them as dependencies

**Comment by wizard-28** [comment]
I actually haven't added `ishw` and `viu` as dependencies yet. So...

**Pull request merged**
