### PR TITLE
added pacget

### PR DESCRIPTION
**Pull request by erikLundstedt**
A fully foss, lightweight fuzzysearching TUI frontend for pacstall using fzf

### CODE REVIEW

**Comment by wizard-28** [comment]
@erikLundstedt When using `removescript`, there needs to be a variable `removescript="yes"` to actually execute the code when the `pacscript` is getting uninstalled.

**Comment by erikLundstedt** [comment]
> You don't need Ubuntu and Debian variables in the script. Also wrap the version in quotes

I do that so it's easier for the user when reading the pacscript

And it's not like it's hurting anything

**Comment by erikLundstedt** [comment]
> Also don't use variables besides the ones pacstall uses. Use paths instead

I can do this, but is there a good reason for it

The way I did it now makes script reuse a lot easier

**Comment by Henryws** [comment]
To be blunt, I won't merge it unless you use paths instead of variables. It may be easier for you, but for the majority of people, it's going to be difficult

**Comment by erikLundstedt** [comment]
> To be blunt, I won't merge it unless you use paths instead of variables. It may be easier for you, but for the majority of people, it's going to be difficult

Okay

**Comment by Henryws** [comment]
Also why `/tmp/pacget`? `/tmp` lives in memory so it gets wiped on reboot or shutdown?

**Comment by erikLundstedt** [comment]
> Also why `/tmp/pacget`? `/tmp` lives in memory so it gets wiped on reboot or shutdown?

thats the point 
the file in/tmp/pacget gets uppdated each run to keep upp to date



only if you implemented my update function into the main program (maybe on -U it also refreshes the packagelist 
)would i be able to change that
(feel free to use non-essential parts of my code, like the update function)

the reason its in the pacscript is to make first run a little bit smoother

**Comment by Henryws** [comment]
Can't you just get pacget to make a directory if it doesn't exist with `mkdir -p /tmp/pacget`? Also `pacstall -U` updates the scripts, not the packagelist. If you think about the AUR, if helpers downloaded a manifest of every package available, it would be gigantic

**Pull request merged**
