### PR TITLE
Add tuner package

### PR DESCRIPTION
**Pull request by louis77**
This package is using the new  `postinst` and `removescript` feature.
It should probably released after these features go into the master branch.

### CODE REVIEW

**Comment by Henryws** [comment]
Did you check that the removescript function works

**Comment by Henryws** [comment]
It probably works, but to be sure, source the file and run `removescript`

**Comment by louis77** [comment]
Ok so I tested it from the Henryws-postinst branch and it basically works.
However, `-R` is sourcing the package from github, which doesn't work with local packages :).
So I think that `-R` should first check if there is a `$PACKAGE.pacscript` in the current directory. 
I hacked that script to use my local pacscript and it properly installed and removed everything.

**Comment by Henryws** [comment]
Remember to run `sudo pacstall -U` to update the scripts so they will work remotely

**Pull request merged**
