### PR TITLE
Update Soundux to 0.2.3

### PR DESCRIPTION
**Pull request by D3SOX**
We require `libpipewire-0.3-dev` to compile it since this version. This is not available in Ubuntu 20's repositories so users might have to a PPA for it. Is there any way to display a message before installing it to inform the users?

### CODE REVIEW

**Comment by D3SOX** [comment]
The workflow looks like it succeeded but it actually failed installing. That's because it runs with Ubuntu 20.04 (see `Unable to locate package libpipewire-0.3-dev`)

**Comment by Henryws** [comment]
Then you should figure out what went wrong. When the package is updated, give it about 5 minutes then run pacstall -Up to upgrade

**Comment by D3SOX** [comment]
As I said it's because it runs with Ubuntu 20.04 (and doesn't have the PPA installed).
It builds fine in my Ubuntu 21.04 VM. It also works in my Ubuntu 20.04 VM with the PipeWire PPA installed.

**Comment by Henryws** [comment]
What about `libpipewire-0.2-dev`? Or is it 0.3 only?

**Comment by Curve** [comment]
> What about `libpipewire-0.2-dev`? Or is it 0.3 only?

We require 0.3. It won't work with 0.2

You can install libpipewire-0.3 on Ubuntu 20.04 with a ppa (`ppa:pipewire-debian/pipewire-upstream`)

**Comment by D3SOX** [comment]
Unrelated but I think you have to tweak something in your workflow to actually fail because as you can see [here](https://github.com/Henryws/pacstall-programs/pull/71/checks?check_run_id=2597911356#step:5:26) it failed but the workflow is `Successful`

**Comment by Henryws** [comment]
Could you compile with a flag to not use piperwire 0.3 then install as a ppa with the `postinst` funcrion?

**Comment by Curve** [comment]
> Could you compile with a flag to not use piperwire 0.3 then install as a ppa with the `postinst` funcrion?

That would completely disable pipewire support for us we need pipewire 0.3 at compile time

**Comment by D3SOX** [comment]
Not sure if this is good practice but I think we could add the PPA inside the `prepare` hook

**Comment by Henryws** [comment]
I can add a ppa function later, but I think doing that is better for now

**Comment by Henryws** [comment]
Merge?

**Comment by D3SOX** [comment]
I'll do a quick test inside a VM

**Comment by Henryws** [comment]
But before the build so it works

**Comment by D3SOX** [comment]
No, it doesn't work because the PPA has to be added before trying to install `libpipewire-0.3-dev`

**Comment by Henryws** [comment]
Sorry. You could install it during the prepare function

**Comment by D3SOX** [comment]
It builds correctly now. If those changes are okay with you it is ready to merge.

**Comment by Henryws** [comment]
I added a ppa system to pacstall. I'll change your scripts to use the new things

**Comment by Henryws** [comment]
I added and tested a pacstall dependency system where you can use other pacscripts as dependencies. Do you want me to update the script?

**Comment by Curve** [comment]
> I added and tested a pacstall dependency system where you can use other pacscripts as dependencies. I added the pipewire pacscript that is version `0.3.27`. Do you want me to update the script?

If everything works, yes please :D

**Comment by D3SOX** [comment]
Your change breaks the package
image
The `pipewire-git` package does not provide the required development headers.

Off-topic: Why is it even named git when it doesn't compile from master? I'm used to that from Arch packages

**Comment by Henryws** [comment]
It worked in a vm for me. I'll figure it out now

**Comment by Henryws** [comment]
I was using this: https://gitlab.freedesktop.org/pipewire/pipewire/. Doesn't that install headers?

**Comment by D3SOX** [comment]
Did you uninstall the PPA and the packages from it before trying?

**Comment by Henryws** [comment]
I'll try that

**Comment by Henryws** [comment]
It works for me

**Comment by D3SOX** [comment]
Fails for me in a Ubuntu 20.04 and 21.04 VM. Sure you don't have it installed via apt? `apt list --installed | grep pipewire`

**Comment by Henryws** [comment]
I'm sure. It gave an error code of 1

**Comment by Henryws** [comment]
Any progress?

**Pull request merged**
