### PR TITLE
[awesome-git] Add package

### PR DESCRIPTION
**Pull request by wizard-28**
This adds [`awesome`](https://github.com/awesomeWM/awesome), the `git` version of it

### CODE REVIEW

**Comment by wizard-28** [comment]
Ok wait, fixing that

**Comment by Henryws** [comment]
You mean wibar? It comes with awesomewm. Also can you use tags instead of git?

**Comment by wizard-28** [comment]
Well for @Leo in our discord, he doesn't have the menu when compiling the pacscript

**Comment by wizard-28** [comment]
I can't not enough space, also can you try it in your machine, And can you please check the dependencies (The dependencies are over half a gigabyte)

**Comment by wizard-28** [comment]
Well, @Leo found out that it the menubar is present

**Comment by Henryws** [comment]
Just change the version number to 4.5 or something besides a git commit number

**Comment by Henryws** [comment]
I think you should just add a number like 4.3.x or something like that

**Comment by Henryws** [comment]
The way pacstall upgrades, it (to the best of my knowledge) won’t accept commit number as a valid version number b/c there just sha256sums that are shortened. I might do something like [this](https://wiki.archlinux.org/title/VCS_package_guidelines) with the `pkgver` function, but for now, just put a version number

**Comment by Henryws** [comment]
That would work

**Comment by wizard-28** [comment]
I don't know about that `stow` error in the end. What do you think?

**Comment by Henryws** [comment]
Should I merge it?

**Comment by wizard-28** [comment]
Since, the `stow`ing worked in bare metal (@Leo and @theAtheistCoder 's computers). I think this is fine to merge

**Pull request merged**
